### PR TITLE
Please release a new version on NuGet

### PR DESCRIPTION
**Pull request by mderriey**
Hi there :wave: 

I'm using version `4.1.1` that is on NuGet right now, but I'm facing an issue where it's not redeploying files when they change.

I wanted to add a failing test to the repo and open a PR, but then found that the current version in the `master` branch works as expected.

Is there any chance you could release a new version on NuGet from the current `master`?

Thanks :+1:

### CODE REVIEW

**Comment by szilardd** [comment]
Are you using this one ? https://www.nuget.org/packages/dbup.onchange-sqlserver/ 

I think it is already created based on `master` branch

**Comment by szilardd** [comment]
Are you referring to the `master` branch from my fork ?

Or the `master` branch from parent repo (https://github.com/DbUp/DbUp) ? The changes from parent repo aren't included completely in my fork.

**Comment by mderriey** [comment]
From your fork.

**Comment by szilardd** [comment]
Deployed version 4.1.2 from `master` branch

Can you check if it fixes your issue ?

https://www.nuget.org/packages/dbup.onchange-sqlserver/

**Comment by mderriey** [comment]
Thanks, the new version of the package fixes the issue we were seeing, i.e scripts were not being redeployed on change :+1:

**Pull request closed without merging**
